on: [workflow_call]
name: "Check"
permissions: {}

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x --source-path=src -e SC3333
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile.custom
          ignore: DL3008,SC3037,DL4006
          failure-threshold: warning
